package Enum;

public enum CardTightBTypes {
    SHIELD_MAIDENS,
    WAR_LONG_SHIPS,
    AN_CRAITE_WARRIORS,
    TRANSFORMED_YOUNG_BERSERKERS,
    DRAGON_HUNTERS,
    BLUE_COMMANDOS,
    POOR_INFANTRY,
    CATAPULTS,
    NAUSICAA_CAVALRY,
    YOUNG_EMISSARIES,
    IMPERA_GUARDS,
}
