package Enum;

public enum PreGameSetDeck {

    DECK_SCROLL_PANE_X_POSITION(1000) ,
    DECK_SCROLL_PANE_Y_POSITION(150) ,
    STORAGE_SCROLL_PANE_X_POSITION(50) ,
    STORAGE_SCROLL_PANE_Y_POSITION(150) ,
    STORAGE_SCROLL_PANE_WIDTH(500) ,
    STORAGE_SCROLL_PANE_HEIGHT(600) ,
    DECK_SCROLL_PANE_WIDTH(500) ,
    DECK_SCROLL_PANE_HEIGHT(600) ,
    MIDDLE_PANE_X_POSITION(575) ,
    MIDDLE_PANE_Y_POSITION(150) ,
    MIDDLE_PANE_WIDTH(400) ,
    MIDDLE_PANE_HEIGHT(600) ,
    CARD_WIDTH(STORAGE_SCROLL_PANE_WIDTH.getValue() / 3) ,
    CARD_HEIGHT(STORAGE_SCROLL_PANE_HEIGHT.getValue() / 2) ,
    LEADER_CARD_WIDTH(200) ,
    LEADER_CARD_HEIGHT(330) ,
    LEADER_CARD_X_POSITION(MIDDLE_PANE_WIDTH.getValue() / 2 - LEADER_CARD_WIDTH.getValue() / 2) ,
    STORAGE_GRID_PAIN_H_GAP(3) ,
    STORAGE_GRID_PANE_V_GAP(3) ,
    DECK_GRID_PANE_H_GAP(3) ,
    DECK_GRID_PANE_V_GAP(3) ,
    LEFT_TEXT_X_POSITION(STORAGE_SCROLL_PANE_X_POSITION.getValue() + STORAGE_SCROLL_PANE_WIDTH.getValue() / 2 - 80) ,
    LEFT_TEXT_Y_POSITION(100) ,
    LEFT_TEXT_SIZE(20) ,
    RIGHT_TEXT_X_POSITION(DECK_SCROLL_PANE_X_POSITION.getValue() + DECK_SCROLL_PANE_WIDTH.getValue() / 2 - 80) ,
    RIGHT_TEXT_Y_POSITION(LEFT_TEXT_Y_POSITION.getValue()) ,
    RIGHT_TEXT_SIZE(LEFT_TEXT_SIZE.getValue()) ,
    FACTION_ICON_X_POSITION(MIDDLE_PANE_X_POSITION.getValue()) ,
    FACTION_ICON_Y_POSITION(10) ,
    FACTION_NAME_TEXT_X_POSITION(FACTION_ICON_X_POSITION.getValue() + 100),
    FACTION_NAME_TEXT_Y_POSITION(FACTION_ICON_Y_POSITION.getValue() + 60),
    FACTION_NAME_TEXT_SIZE(30) ,
    CHANGE_FACTION_X_POSITION(730) ,
    CHANGE_FACTION_Y_POSITION(800) ,
    CHANGE_FACTION_GRID_PANE_H_GAP(3) ,
    CHANGE_FACTION_GRID_PANE_V_GAP(3) ,
    CHANGE_FACTION_GRID_PANE_WIDTH(200) ,
    CHANGE_FACTION_GRID_PANE_HEIGHT(200) ,
    CHANGE_FACTION_GRID_PANE_X_POSITION(300) ,
    CHANGE_FACTION_GRID_PANE_Y_POSITION(300) ,
    CHANGE_LEADER_GRID_PANE_X_POSITION(300) ,
    CHANGE_LEADER_GRID_PANE_Y_POSITION(300) ,
    CHANGE_LEADER_GRID_PANE_H_GAP(3) ,
    CHANGE_LEADER_GRID_PANE_V_GAP(3)
    ;


    private final double value;
    PreGameSetDeck(double value) {
        this.value = value;
    }
    public double getValue() {
        return value;
    }
}
