package Enum;

public enum RequestTypes {
    LOGIN,
    REGISTER,
    LOGIN_WITH_SEC_QUESTIONS,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_EMAIL,
    CHANGE_NICKNAME,
    LEADERBOARD_REQUEST,
    SET_SEC_QUESTIONS,
    START_GAME_WITH,
    SET_CARDS_PREGAME,
    SEND_FRIEND_REQUEST,
    ANSWER_TO_FRIEND_REQUEST,
    BLOCK_REQUEST,
    UNBLOCK_REQUEST,
    FOLLOW_REQUEST,
    UNFOLLOW_REQUEST,
    LOGOUT,


}
